services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports: ["8000:8000"]
    env_file:
      - ../backend/.env
    volumes:
      - ../backend/app:/app/app:rw
      - ../uploads:/app/uploads:rw
    depends_on:
      - mongo

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports: ["5173:5173"]
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ../frontend:/app:rw
      - /app/node_modules
    depends_on:
      - backend

  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes:
      - ../mongodb-data:/data/db
