services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports: ["8000:8000"]

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports: ["5173:5173"]
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on: [backend]
